name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write # এটি GitHub-কে ফাইল রাইট করার পারমিশন দিবে

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release --base-href "/portfolio_website/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
